import { Checklist } from "../type";

const Boeing738: Checklist = {
  manufacturer: "Boeing",
  model: "737-700/800",
  checklists: [
    {
      name: "PRE FLIGHT",
      checklist: [
        { item: "PARKING BRAKE", expect: "SET" },
        { item: "BATTERY", expect: "GUARD CLOSED" },
        { item: "STANDBY POWER", expect: "GUARD CLOSED" },
        { item: "L CENTER FUEL PUMP", expect: "AS REQUIRED" },
        { item: "L AFT FUEL PUMP", expect: "AS REQUIRED" },
        { item: "APU", expect: "START" },
        { item: "APU GEN", expect: "ON" },
        { item: "POSITION LIGHTS", expect: "STEADY" },
        { item: "LOGO LIGHT", expect: "AS REQUIRED" },
        { item: "CABIN LIGHTS", expect: "AS REQUIRED" },
        { item: "EMER EXIT LIGHTS", expect: "GUARD CLOSED" },
        { item: "PASSENGER SIGNS", expect: "ON" },
        { item: "PACKS", expect: "AUTO / HIGH" },
        { item: "IRS MODE SELECTORS", expect: "OFF > NAV" },
        { item: "FMC", expect: "SET" },
        { item: "Flight-plan Clearance", expect: "REQUESTED" },
        { item: "TRANSPONDER", expect: "SET" },
        { item: "IAS / MACH SPEED", expect: "SET" },
        { item: "HDG / TAKEOFF RWY", expect: "SET" },
        { item: "INITIAL ALT", expect: "SET" },
        { item: "YAW DAMPER", expect: "ON" },
        { item: "WINDOW HEAT", expect: "ON" },
        { item: "FLIGHT ALTITUDE", expect: "SET" },
        { item: "LANDING ALTITUDE", expect: "SET" },
        { item: "FLIGHT DIRECTORS", expect: "ON" },
        { item: "LNAV", expect: "AS REQUIRED" },
        { item: "VNAV", expect: "AS REQUIRED" },
        { item: "MINIMUMS REF", expect: "BARO or RADIO" },
        { item: "MINIMUMS", expect: "SET" },
        { item: "ALTIMETER REF", expect: "IN or HPA" },
        { item: "AUTO BRAKE", expect: "RTO" },
        { item: "COM RADIOS", expect: "SET" },
        { item: "DOORS", expect: "CLOSED" },
      ],
    },
    {
      name: "BEFORE START",
      checklist: [
        { item: "Pushback & Startup Clearance", expect: "REQUESTED" },
        { item: "AUTOTHROTTLE", expect: "ARM" },
        { item: "L & R C FUEL PUMPS", expect: "AS REQUIRED" },
        { item: "A & F FUEL PUMPS ", expect: "ON" },
        { item: "ELEC HYD PUMPS", expect: "ON" },
        { item: "ANTI COLLISION LIGHT", expect: "ON" },
        { item: "PARKING BRAKE", expect: "SET" },
        { item: "GROUND EQUIPMENT", expect: "REMOVED" },
        { item: "ENGINE AREA", expect: "CLEAR" },
      ],
    },
    {
      name: "ENGINE START",
      checklist: [
        { item: "SEC DISPLAY UNIT", expect: "ENGINE" },
        { item: "PACKS", expect: "OFF" },
        { item: "ENGINE 1 START SWITCH", expect: "GND" },
        { item: "ENGINE 1 FUEL CONTROL LEVER", expect: "RUN" },
        { item: "ENGINE 2 START SWITCH", expect: "GND" },
        { item: "ENGINE 2 FUEL CONTROL LEVER", expect: "RUN" },
      ],
    },
    {
      name: "BEFORE TAXI",
      checklist: [
        { item: "GENERATORS 1 & 2", expect: "ON" },
        { item: "PROBE HEAT", expect: "ON" },
        { item: "WING ANTI ICE", expect: "AS REQUIRED" },
        { item: "ENGINE ANTI ICE", expect: "AS REQUIRED" },
        { item: "PACKS", expect: "AUTO" },
        { item: "ISOLATION VALVE", expect: "AUTO" },
        { item: "APU BLEED", expect: "OFF" },
        { item: "APU", expect: "OFF" },
        { item: "ENG START SWITCHES", expect: "CONT" },
        { item: "FLAPS", expect: "AS REQUIRED" },
        { item: "ELEVATOR TRIM", expect: "SET FOR TAKE-OFF" },
        { item: "FLIGHT CONTROLS", expect: "FREE AND CORRECT" },
        { item: "RECALL", expect: "CHECK" },
        { item: "LOWER DISPLAY UNIT (DU)", expect: "OFF" },
        { item: "Taxi Clearance", expect: "REQUESTED" },
        { item: "TAXI LIGHTS", expect: "ON" },
        { item: "RWY TURN-OFF LIGHTS", expect: "AS REQUIRED" },
      ],
    },
    {
      name: "TAXI",
      checklist: [
        { item: "BRKS/GYRO/TURN COORDINATOR", expect: "CHECK" },
      ],
    },
    {
      name: "BEFORE TAKE-OFF",
      checklist: [
        { item: "PARKING BRAKE", expect: "SET" },
        { item: "FUEL FLOW", expect: "RESET, then RATE" },
        { item: "C FUEL PUMPS", expect: "AS REQUIRED" },
        { item: "DE-ICE", expect: "AS REQUIRED" },
        { item: "CABIN LIGHTS", expect: "AS REQUIRED" },
        { item: "FLIGHT INSTRUMENTS", expect: "CHECK" },
        { item: "ENGINE INSTRUMENTS", expect: "CHECK" },
        { item: "TAKE-OFF DATA", expect: "(V1, VR, V2) CHECK" },
        { item: "NAV EQUIPMENT", expect: "CHECK" },
        { item: "Takeoff Clearance", expect: "CHECK" },
        { item: "LANDING LIGHTS", expect: "ON" },
        { item: "STROBE LIGHT", expect: "ON" },
        { item: "TAXI LIGHTS", expect: "OFF" },
        { item: "TRANSPONDER", expect: "TA/RA" },
        { item: "TFC", expect: "PUSH ON" },
        { item: "CLOCK", expect: "START" },
      ],
    },
    {
      name: "AFTER TAKE-OFF",
      checklist: [
        { item: "POSITIVE RATE OF CLIMB", expect: "GEAR UP" },
        { item: "AUTO-BRAKE", expect: "OFF" },
        { item: "ENGINE START SWITCHES", expect: "OFF" },
        { item: "GEAR LEVER", expect: "OFF POSITION" },
        { item: "RWY TURN-OFF LIGHTS", expect: "OFF" },
        { item: "CABIN LIGHTS", expect: "AS REQUIRED" },
      ],
    },
    {
      name: "CLIMB",
      checklist: [
        { item: "ALTIMETER", expect: "PUSH TO SET STD" },
        { item: "LANDING LIGHTS", expect: "OFF" },
        { item: "FASTEN SEAT BELTS ", expect: "OFF" },
        { item: "C FUEL PUMPS", expect: "AS REQUIRED" }
      ],
    },
    {
      name: "CRUISE",
      checklist: [
        { item: "ENGINE & INSTRUMENTS", expect: "MONITOR" },
        { item: "FUEL QUANTITY", expect: "CHECK" },
        { item: "LIGHTS", expect: "AS REQUIRED" },
      ],
    },
    {
      name: "BEFORE TOD",
      checklist: [
        { item: "ATIS / AIRPORT INFORMATION", expect: "CHECK" },
        { item: "ALTIMETER", expect: "CHECK" },
        { item: "RADIOS", expect: "SET" },
        { item: "RESET MCP ALTITUDE", expect: "CHECK" },
        { item: "FMC APPR SPEED REF", expect: "SET" },
        { item: "LOCALIZER FREQ", expect: "SET" },
        { item: "ILS LOC COURSE", expect: "SET" },
      ],
    },
    {
      name: "DESCENT",
      checklist: [
        { item: "DE-ICE", expect: "AS REQUIRED" },
        { item: "LANDING ALT", expect: "CHECK" },
        { item: "RECALL", expect: "CHECK" },
        { item: "RADIO ALT / BARO MIN", expect: "SET, CHECK" },
        { item: "AUTO BRAKE", expect: "AS REQUIRED" },
        { item: "ALTIMETER", expect: "RESET TO LOCAL" },
        { item: "LANDING LIGHTS", expect: "ON" },
        { item: "PASSENGER SIGNS", expect: "ON" },
      ],
    },
    {
      name: "APPROACH",
      checklist: [
        { item: "ALTIMETER", expect: "CHECK" },
        { item: "LOCALIZER FREQ", expect: "CHECK" },
        { item: "LOCALIZER COURSE", expect: "CHECK" },
        { item: "APP", expect: "ARM" },
        { item: "GLIDESLOPE ALIVE", expect: "GEAR DOWN" },
        { item: "FLAPS", expect: "15" },
        { item: "SPEED BRAKE", expect: "ARM" },
        { item: "2ND AUTOPILOT", expect: "ARM (when ILS established)" },
        { item: "ENGINE START SWITCHES", expect: "CONT" },
        { item: "LANDING FLAPS", expect: "SET" },
      ],
    },
    {
      name: "BEFORE LANDING",
      checklist: [
        { item: "GO-AROUND ALTITUDE", expect: "SET" },
        { item: "RWY TURN-OFF LIGHTS", expect: "ON" },
        { item: "LANDING GEAR", expect: "CHECK DOWN" },
        { item: "AUTOPILOT", expect: "AS REQUIRED" },
        { item: "AUTO-THRUST", expect: "AS REQUIRED" },
      ],
    },
    {
      name: "AFTER LANDING",
      checklist: [
        { item: "TRANSPONDER", expect: "OFF" },
        { item: "FLAPS", expect: "RETRACT" },
        { item: "SPEED BRAKE", expect: "DOWN" },
        { item: "LANDING LIGHTS", expect: "OFF" },
        { item: "STROBE LIGHTS", expect: "OFF" },
        { item: "TAXI LIGHTS", expect: "ON" },
        { item: "CABIN LIGHTS", expect: "AS REQUIRED" },
        { item: "ANTI ICE", expect: "AS REQUIRED" },
        { item: "APU", expect: "START / CHECK RUN" },
        { item: "PROBE HEAT", expect: "OFF" },
        { item: "ENG START SWITCHES", expect: "OFF" },
        { item: "AUTO-BRAKE", expect: "OFF" },
        { item: "RWY TURNOFF LIGHTS", expect: "OFF" },
        { item: "APU GEN", expect: "ON / CHECK VOLTS" },
        { item: "TAXI LIGHTS", expect: "OFF" },
      ],
    },
    {
      name: "PARKING / SHUTDOWN",
      checklist: [
        { item: "PARKING BRAKES", expect: "SET" },
        { item: "ENGINE FUEL CONTROL LEVERS", expect: "OFF" },
        { item: "GROUND CONTACT", expect: "ESTABLISH" },
        { item: "GROUND OPERATIONS", expect: "AS REQUIRED" },
        { item: "PASSENGER SIGNS", expect: "OFF" },
        { item: "APU BLEED AIR", expect: "ON" },
        { item: "ANTI COLLISION LIGHT", expect: "OFF" },
        { item: "FUELPUMPS", expect: "OFF" },
        { item: "L AFT FUEL PUMP", expect: "ON" },
        { item: "ANTI-ICE", expect: "OFF" },
        { item: "ELEC HYD PUMPS", expect: "OFF" },
        { item: "ISOLATION VALVE", expect: "OPEN" },
        { item: "FLIGHT DIRECTOR", expect: "OFF" },
        { item: "ELECTRICAL POWER", expect: "ESTABLISH" },
        { item: "EXTERIOR LIGHTS", expect: "AS REQUIRED" },
        { item: "DOORS", expect: "OPEN" },
      ],
    },
    {
      name: "SECURING AIRCRAFT",
      checklist: [
        { item: "IRS MODE SELECTORS", expect: "OFF" },
        { item: "APU", expect: "OFF" },
        { item: "L AFT FUEL PUMP", expect: "OFF" },
        { item: "EMERGENCY EXIT LIGHTS", expect: "OFF" },
        { item: "WINDOW HEAT", expect: "OFF" },
        { item: "PACKS", expect: "OFF" },
        { item: "CABIN LIGHTS", expect: "OFF" },
        { item: "EXTERIOR LIGHTS", expect: "OFF" },
        { item: "STANDBY POWER", expect: "OFF" },
        { item: "BATTERY", expect: "OFF" },
      ],
    },
  ],
};

export default Boeing738;
