import { Checklist } from "../type";

const Cessna152: Checklist = {
  manufacturer: "Cessna",
  model: "Citation CJ4",
  checklists: [
    {
      name: "BEFORE START",
      checklist: [
        { item: "Battery Switch", expect: "ON" },
        { item: "Emergency Lights Switch", expect: "ARMED" },
        { item: "Standby Flight Display Switch", expect: "ON" },
        { item: "Avionics Switch", expect: "DISPATCH" },
        { item: "Parking Brake", expect: "SET" },
        { item: "Wheel Chocks", expect: "REMOVE" },
        { item: "Cabin Door", expect: "CLOSED" },
        { item: "Passenger Briefing", expect: "COMPLETE" },
        { item: "Seats/Belts/Pedals", expect: "ADJUST/SECURE" },
        { item: "Exterior Lights", expect: "AS REQUIRED" },
        { item: "EICAS", expect: "CHECK" },
        { item: "FMS", expect: "CHECK/SET" },
        { item: "Climate Control Selector", expect: "OFF" },
      ],
    },
    {
      name: "START",
      checklist: [
        { item: "Throttles", expect: "IDLE" },
        { item: "Engine Starter Button", expect: "PUSH" },
        { item: "Engine Run/Stop", expect: "RUN" },
        { item: "ITT", expect: "CHECK FOR RISE" },
        { item: "EICAS", expect: "CHECK" },
        { item: "Opposite Engine", expect: "START" },
        { item: "External Power", expect: "DISCONNECTED" },
        { item: "Electrical System", expect: "CHECK" },
      ],
    },
    {
      name: "BEFORE TAXI",
      checklist: [
        { item: "Avionics Switch", expect: "ON" },
        { item: "Climate Control Selector", expect: "NORM" },
        { item: "PASS Light Safety Button", expect: "ON" },
        { item: "Trims", expect: "CHECK/SET" },
        { item: "Flight Controls", expect: "FREE/CORRECT" },
        { item: "Speedbrake/Ground Spoilers", expect: "CHECK" },
        { item: "Flaps", expect: "CHECK/SET" },
        { item: "Hydraulic Pressure", expect: "CHECK" },
        { item: "Engine Only Anti-Ice", expect: "AS REQUIRED" },
        { item: "Takeoff Data", expect: "CONFIRM/SET" },
        { item: "Avionics", expect: "CHECK/SET" },
        { item: "Autopilot", expect: "ENGAGE/DISCONNECT" },
        { item: "Altimeter", expect: "SET/CHECK" },
        { item: "Pressurization", expect: "VERIFY/SET" },
        { item: "EICAS", expect: "CHECK" },
        { item: "Aft Divider Doors", expect: "Latched Open" },
      ],
    },
    {
      name: "TAXI",
      checklist: [
        { item: "Exterior Lights", expect: "AS REQUIRED" },
        { item: "Brakes", expect: "APPLY/HOLD" },
        { item: "Parking Brake", expect: "RELEASE" },
        { item: "Brakes", expect: "CHECK" },
        { item: "Nose Wheel Steering", expect: "CHECK" },
        { item: "Flight Instruments", expect: "CHECK" },
      ],
    },
    {
      name: "BEFORE TAKEOFF",
      checklist: [
        { item: "Ice Protection System", expect: "CHECK" },
        { item: "Rudder Bias System", expect: "CHECK" },
        { item: "Seats", expect: "UPRIGHT/OUTBOARD" },
        { item: "Flaps", expect: "CHECK/SET" },
        { item: "Speed Brakes", expect: "0%" },
        { item: "Trims (3)", expect: "SET FOR TAKEOFF" },
        { item: "Crew Briefing", expect: "COMPLETE" },
        { item: "TCAS", expect: "TA/RA" },
        { item: "Radar", expect: "AS REQUIRED" },
        { item: "GA Button", expect: "PUSH" },
        { item: "Battery Amps", expect: "VERIFY 20 OR LESS" },
        { item: "Ice Protection System", expect: "AS REQUIRED" },
        { item: "Pitot/Static Heat Buttons", expect: "ON" },
        { item: "Exterior Lights", expect: "AS REQUIRED" },
        { item: "EICAS", expect: "CHECK" },
      ],
    },
    {
      name: "TAKEOFF",
      checklist: [
        { item: "Throttles", expect: "TAKEOFF" },
        { item: "N1 Command Bugs", expect: "GREEN CHEVRON" },
        { item: "Brakes", expect: "RELEASE" },
        { item: "Control Wheel", expect: "ROTATE AT VR" },
      ],
    },
    {
      name: "AFTER TAKEOFF/CLIMB",
      checklist: [
        { item: "Landing Gear", expect: "UP" },
        { item: "Flaps", expect: "0" },
        { item: "Throttles", expect: "CLIMB" },
        { item: "Yaw Damper", expect: "ON" },
        { item: "Autopilot", expect: "AS DESIRED" },
        { item: "Ice Protection Systems", expect: "AS REQUIRED" },
        { item: "PASS Lights Buttons", expect: "AS REQUIRED" },
        { item: "Landing Lights Button", expect: "AS REQUIRED" },
        { item: "Pressurization", expect: "CHECK" },
        { item: "Altimeters", expect: "SET/CROSSCHECK" },
      ],
    },
    {
      name: "CRUISE",
      checklist: [
        { item: "Throttles", expect: "AS REQUIRED" },
        { item: "Pressurization", expect: "CHECK" },
        { item: "Ice Protection Systems", expect: "AS REQUIRED" },
      ],
    },
    {
      name: "DESCENT",
      checklist: [
        { item: "Pressurization", expect: "VERIFY/SET LDG ELEV" },
        { item: "Ice Protection Systems", expect: "AS REQUIRED" },
        { item: "Altimeters", expect: "SET/CROSSCHECK" },
        { item: "Exterior Lights", expect: "AS REQUIRED" },
      ],
    },
    {
      name: "APPROACH",
      checklist: [
        { item: "Landing Data", expect: "CONFIRM" },
        { item: "Crew Briefing", expect: "COMPLETE" },
        { item: "Avionics/Flight Instruments", expect: "CHECK" },
        { item: "Minimums", expect: "SET" },
        { item: "Fuel Transfer Selector", expect: "OFF" },
        { item: "Exterior Lights", expect: "AS REQUIRED" },
        { item: "Ice Protection Systems", expect: "AS REQUIRED" },
        { item: "Flaps", expect: "15" },
        { item: "Passenger Briefing", expect: "COMPLETE" },
        { item: "Seats", expect: "UPRIGHT AND OUTBOARD" },
        { item: "Seat Belts", expect: "ADJUSTED/SECURE" },
        { item: "PASS Lights Safety Button", expect: "ON" },
        { item: "Pressurization", expect: "< 0.5 PSI BEFORE LANDING" },
      ],
    },
    {
      name: "BEFORE LANDING",
      checklist: [
        { item: "Landing Gear", expect: "DOWN (3 GREEN)" },
        { item: "Flaps", expect: "35" },
        { item: "Speed Brakes", expect: "0%" },
        { item: "Airspeed", expect: "VREF" },
        { item: "Autopilot and Yaw Damper", expect: "DISENGAGE" },
      ],
    },
    {
      name: "LANDING",
      checklist: [
        { item: "Throttles", expect: "IDLE" },
        { item: "Brakes (After NLG Touch)", expect: "APPLY" },
        { item: "Ground Spoilers", expect: "EXTEND" },
      ],
    },
    {
      name: "GO AROUND",
      checklist: [
        { item: "GA Button", expect: "PUSH" },
        { item: "Throttles", expect: "TAKEOFF" },
        { item: "Pitch Attitude", expect: "7.5 THEN AS REQUIRED" },
        { item: "Flaps", expect: "15" },
        { item: "Landing Gear", expect: "UP" },
        { item: "Flaps", expect: "AS REQUIRED" },
        { item: "Airspeed", expect: "AS REQUIRED" },
        { item: "Throttles", expect: "AS REQUIRED" },
        { item: "Yaw Damper", expect: "ON" },
        { item: "Autopilot", expect: "AS DESIRED" },
      ],
    },
    {
      name: "AFTER LANDING",
      checklist: [
        { item: "Speedbrakes", expect: "0%" },
        { item: "Flaps", expect: "0" },
        { item: "Pitot/Static Heat Buttons", expect: "OFF" },
        { item: "Ice Protection Systems", expect: "OFF/AS REQUIRED" },
        { item: "Radar", expect: "STANDBY" },
        { item: "Exterior Lights", expect: "AS REQUIRED" },
      ],
    },
    {
      name: "SHUTDOWN",
      checklist: [
        { item: "Parking Brake", expect: "SET/WHEELS CHOCKED" },
        { item: "Emergency Lights Switch", expect: "OFF" },
        { item: "Stby Flight Display Switch", expect: "OFF" },
        { item: "Avionics Switch", expect: "OFF" },
        { item: "Climate Control Selector", expect: "OFF" },
        { item: "Ice Protection Systems (All)", expect: "OFF" },
        { item: "Throttles", expect: "IDLE" },
        { item: "Engine Run/Stop Buttons (Both)", expect: "STOP" },
        { item: "Exterior Lights", expect: "OFF" },
        { item: "Battery Switch", expect: "OFF" },
        { item: "Control Lock", expect: "AS REQUIRED" },
        { item: "Engine Covers (After Engine Cool)", expect: "INSTALL" },
      ],
    },
  ],
};

export default Cessna152;
