import { Checklist } from "../type";

const Learjet35: Checklist = {
  manufacturer: "Learjet",
  model: "Learjet 35",
  checklists: [
    {
      name: "START",
      checklist: [
        { item: "Fuel Qty, Bal, Counter", expect: "CHECKED / ZEROED" },
        { item: "Thrust Levers", expect: "CUTOFF" },
        { item: "Fuel Computers", expect: "ON" },
        { item: "Beacon", expect: "ON" },
        { item: "Batts", expect: "MIN 24V" },
        { item: "Inverters", expect: "ON" },
        { item: "Aux Heat", expect: "OFF" },
        { item: "Air conditioning", expect: "OFF" },
        { item: "Cabin Door", expect: "CLOSED/LT OUT" },
        { item: "Belts and Harnesses", expect: "ON RT/ON LT" },
        { item: "Parking Brake.", expect: "SET" },
        { item: "Hyd Pump", expect: "OFF" },
        { item: "Cell Phones", expect: "OFF" },
      ],
    },
    {
      name: "BEFORE TAXI - TWO ENGINES",
      checklist: [
        { item: "GPU", expect: "DISCONNECTED" },
        { item: "Generators", expect: "ONLINE" },
        { item: "Starter Disengagement", expect: "LT OUT" },
        { item: "Fuel Computers", expect: "CHECKED" },
        { item: "Spoileron / Spoilers", expect: "CHECKED" },
        { item: "Anti-Ice", expect: "CHECKED" },
        { item: "No Smoking/Seat Belt", expect: "ON" },
        { item: "Windshield Heat", expect: "PURGED / OFF/ IN" },
        { item: "Gyro Flags", expect: "CLEAR RT / CLEAR LT" },
        { item: "HYD Press", expect: "CHECK" },
        { item: "Circuit Breakers", expect: "CHECK RT / CHECK LT" },
        { item: "Parking Brake", expect: "RELEASE" },
      ],
    },
    {
      name: "BEFORE TAXI - SINGLE ENGINE",
      checklist: [
        { item: "GPU", expect: "DISCONNECTED" },
        { item: "Generator", expect: "ONLINE" },
        { item: "Starter Disengagement", expect: "LT OUT" },
        { item: "Spoileron / Spoilers", expect: "CHECKED" },
        { item: "No Smoking/Seat Belt", expect: "ON" },
        { item: "Yaw Dampers", expect: "CHECKED" },
        { item: "Windshield Heat", expect: "PURGED / OFF/ IN" },
        { item: "Gyro Flags", expect: "CLEAR RT / CLEAR LT" },
        { item: "HYD Press", expect: "CHECK" },
        { item: "Circuit Breakers", expect: "CHECK RT / CHECK LT" },
        { item: "Parking Brake", expect: "RELEASE" },
      ],
    },
    {
      name: "TAXI - TWO ENGINES",
      checklist: [
        { item: "Departure Runway", expect: "BUGGED/VERIFIED" },
        { item: "Transponder", expect: "AS REQ" },
        { item: "Brakes and Steering", expect: "CHECKED" },
        { item: "Anti-Skid", expect: "ON /LIGHTS OUT" },
        { item: "Flight Controls", expect: "CHECKED" },
        { item: "Flight Instruments", expect: "CHECKED" },
        { item: "Spoilers", expect: "RETRACTED /LIGHT OUT" },
        { item: "Flaps", expect: "SET 8° OR 20° /VERIFIED" },
        { item: "Trims", expect: "(3) SET/ PRIMARY /LT OUT" },
        { item: "Fuel Qty/Balance", expect: "CHECKED" },
        { item: "Current Limiters", expect: "LIGHTS OUT" },
        { item: "Electrical Panel", expect: "CHECKED" },
        { item: "Engine Instruments", expect: "CHECKED" },
        { item: "Avionics", expect: "SET / REVIEWED" },
        { item: "Thrust Reversers", expect: "CHECKED & STOWED" },
        { item: "Speed Bugs / N1 ", expect: "SET___ /VERIFIED" },
        { item: "Pressurization", expect: "SET___ /VERIFIED" },
        { item: "Bleed Air/Cabin Air", expect: "ON" },
        { item: "Cabin Temp Controls", expect: "SET" },
        { item: "Takeoff Briefing", expect: "COMPLETE" },
      ],
    },
    {
      name: "TAXI - SINGLE ENGINE",
      checklist: [
        { item: "Departure Runway", expect: "BUGGED/VERIFIED" },
        { item: "Transponder", expect: "AS REQ" },
        { item: "Brakes and Steering", expect: "CHECKED" },
        { item: "Anti-Skid", expect: "ON /LIGHTS OUT" },
        { item: "Flight Controls", expect: "CHECKED" },
        { item: "Flight Instruments", expect: "CHECKED" },
        { item: "Spoilers", expect: "RETRACTED /LIGHT OUT" },
        { item: "Flaps", expect: "SET 8° OR 20° /VERIFIED" },
        { item: "Trims", expect: "(3) SET/ PRIMARY /LT OUT" },
        { item: "Avionics", expect: "SET / REVIEWED" },
        { item: "Speed Bugs / N1 ", expect: "SET___ /VERIFIED" },
        { item: "Pressurization", expect: "SET___ /VERIFIED" },
        { item: "Bleed Air/Cabin Air", expect: "ON" },
        { item: "Cabin Temp Controls", expect: "SET" },
      ],
    },
    {
      name: "READY TO START SECOND ENGINE",
      checklist: [
        { item: "Air Conditioner", expect: "OFF" },
        { item: "Aux Heat", expect: "OFF" },
        { item: "Engine", expect: "START" },
        { item: "Generators", expect: "ONLINE" },
        { item: "Starter Disengagement", expect: "LIGHTS OUT" },
        { item: "Current Limiters", expect: "LIGHTS OUT" },
        { item: "Electrical Panel", expect: "CHECKED" },
        { item: "Engine Instruments", expect: "CHECKED" },
        { item: "Thrust Reversers", expect: "CHECKED & STOWED" },
        { item: "Fuel Computers", expect: "CHECKED" },
        { item: "Anti-Ice", expect: "CHECKED" },
        { item: "Fuel Panel", expect: "CHECKED & BALANCED" },
        { item: "Takeoff Briefing", expect: "COMPLETE" },
      ],
    },
    {
      name: "BEFORE TAKEOFF",
      checklist: [
        { item: "Parking Brake", expect: "RELEASED" },
        { item: "Transponder/TCAS/TAWS", expect: "ON" },
        { item: "Thrust Reversers", expect: "ARM" },
        { item: "Pitot Heat", expect: "ON" },
        { item: "Anti-Ice", expect: "AS REQ" },
        { item: "Lights", expect: "ON" },
        { item: "Cabin Air", expect: "ON" },
        { item: "Stall Warning", expect: "ON" },
        { item: "Ignition", expect: "ON" },
        { item: "Annunciator Panel", expect: "NORMAL" },
        { item: "Departure Runway", expect: "BUGS ALIGNED/VERIFIED" },
        { item: "Before Takeoff Check", expect: "COMPLETE" },
      ],
    },
    {
      name: "CLIMB",
      checklist: [
        { item: "Landing Gear", expect: "UP" },
        { item: "Yaw Damper", expect: "ENGAGED" },
        { item: "Thrust Reversers", expect: "OFF" },
        { item: "Flaps", expect: "UP" },
        { item: "Pressurization", expect: "CHECK" },
        { item: "Ignition", expect: "AS REQ" },
        { item: "Landing/Taxi Lights", expect: "OFF" },
        { item: "Autopilot APPR Lt", expect: "OUT" },
        { item: "Hydraulic Pressure", expect: "CHECK" },
        { item: "Angle of Attack Indicator", expect: "XCHECK" },
      ],
    },
    {
      name: "CLIMB - TRANSITION ALT",
      checklist: [
        { item: "Altimeters", expect: "STD/XCHECK" },
        { item: "Recog Light", expect: "OFF" },
        { item: "Air Conditioner", expect: "ON" },
        { item: "Oxygen Pressure", expect: "CHECK" },
      ],
    },
    {
      name: "10.000FT",
      checklist: [
        { item: "No Smoking / Seat Belt Sign", expect: "AS REQ" },
        { item: "Pressurization", expect: "CHECKED" },
      ],
    },
    {
      name: "DESCENT",
      checklist: [
        { item: "Windshield Heat/ Aux Defog", expect: "AS REQ" },
        { item: "Cabin Controller", expect: "FIELD ELEVATION" },
        { item: "Anti-Ice Systems", expect: "AS REQ" },
      ],
    },
    {
      name: "APPROACH",
      checklist: [
        { item: "Altimeters", expect: "SET___-XCHECK" },
        { item: "Recog Lt", expect: "ON" },
        { item: "Belts and Harnesses", expect: "ON RT/ON LT" },
        { item: "Pressurization", expect: "CHECK" },
        { item: "No Smoking / Seat Belt Sign", expect: "ON" },
        { item: "Pax Briefing / Cabin Secured", expect: "COMPLETE" },
        { item: "Circuit Breakers", expect: "CHECK RT/CHECK LT" },
        { item: "Hydraulic & Emerg Air Press", expect: "CHECKED" },
        { item: "Landing Data", expect: "COMPUTED & SET" },
        { item: "Fuel", expect: "BALANCED" },
        { item: "Approach Briefing", expect: "COMPLETE" },
      ],
    },
    {
      name: "BEFORE LANDING",
      checklist: [
        { item: "Flaps", expect: "8° OR 20°" },
        { item: "Landing Gear", expect: "DOWN-3 GREEN-NO RED" },
        { item: "Ignition", expect: "ON" },
        { item: "Landing / Taxi Lts", expect: "ON" },
        { item: "Anti-Skid", expect: "ON" },
        { item: "Thrust Reversers", expect: "ARM" },
        { item: "Flaps", expect: "LANDING" },
        { item: "Hyd Press", expect: "CHECKED" },
        { item: "Autopilot", expect: "DISENGAGED" },
        { item: "Yaw Damper", expect: "OFF" },
      ],
    },
    {
      name: "AFTER LANDING",
      checklist: [
        { item: "Stall Warning", expect: "OFF" },
        { item: "Ignitions", expect: "STBY" },
        { item: "Thrust Reversers", expect: "DISARM" },
        { item: "Cabin Air", expect: "OFF" },
        { item: "Pitot Heat", expect: "OFF" },
        { item: "Windshield, Defog, Nacs, Stab/Wing", expect: "AS REQ" },
        { item: "Lights", expect: "AS REQ" },
        { item: "One Thrust Lever (Optional)", expect: "CUTOFF" },
        { item: "Hydraulic Press", expect: "CHECK" },
        { item: "Spoilers", expect: "RETRACT" },
        { item: "Flaps", expect: "UP" },
        { item: "Unnecessary Avionics", expect: "OFF" },
        { item: "Transponder", expect: "AS REQ" },
      ],
    },
    {
      name: "SHUTDOWN",
      checklist: [
        { item: "Parking Brake", expect: "AS REQ" },
        { item: "Anti-Ice", expect: "OFF" },
        { item: "Transponder", expect: "STBY" },
        { item: "Avionics", expect: "OFF" },
        { item: "Standby Gyro", expect: "CAGED" },
        { item: "Emergency Battery", expect: "OFF" },
        { item: "Freon Air", expect: "OFF" },
        { item: "Thrust Levers", expect: "CUTOFF" },
        { item: "Start-Gen Switches", expect: "OFF" },
        { item: "Inverters", expect: "OFF" },
        { item: "Fuel Transfer", expect: "OFF" },
        { item: "Crossflow Valve", expect: "CLOSED" },
        { item: "Beacon Lt", expect: "OFF" },
        { item: "Batteries", expect: "OFF" },
        { item: "Control Lock", expect: "INSTALL" },
        { item: "Chocks", expect: "INSTALL" },
        { item: "Parking Brake", expect: "OFF" },
      ],
    },
  ],
};

export default Learjet35;
